Fixed installation test snippet
The original version fails with:

    org.mozilla.javascript.EcmaError: TypeError: Cannot find function createHttpServer in object [object Object]. (file:/Users/skuro/REMOVEME/vertx.js#10)

It seems to me that the `createHttpServer` method is actually found in the `vertx/http` include instead of the plain `vertex` one that the documentation mentions.